### ISSUE TITLE
镜像接口报错

### ISSUE THREAD

**Issue by yaaamo** [TencentCloud/tencentcloud-sdk-java#1]
[TencentCloudSDKException]message:java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 17 column 30  requestId:
	at com.tencentcloudapi.cvm.v20170312.CvmClient.DescribeImages(CvmClient.java:250)
	at cn.cloudbest.iclouds.qcloud.service.impl.QcloudImageServiceImpl.listImages(QcloudImageServiceImpl.java:25)
	at cn.cloudbest.iclouds.qcloud.compute.DescribeImageTest.images(DescribeImageTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by yaaamo** [comment]
报错原因，接口返回值 Platform是一个字符串，JSON解析时 Image对象 Platform是一个数组Platform[]，所以JSON解析出错。

**Comment by yaaamo** [comment]
/**
    * 镜像来源平台
    */
    @SerializedName("Platform")
    @Expose
    private String [] Platform;
    

     {
                "ImageId": "img-l5dbtb0r",
                "OsName": "CentOS 7.3 64位 + 深度学习环境",
                "ImageSize": 50,
                "ImageType": "PUBLIC_IMAGE",
                "CreatedTime": null,
                "ImageState": "NORMAL",
                "ImageSource": "OFFICIAL",
                "ImageName": "CentOS 7.3 64位 + 深度学习环境",
                "ImageDescription": "CentOS 7.3 64位 + 深度学习环境",
                "ImageCreator": null,
                "isSupportCloudinit": false,
                "Platform": "CentOS",
                "Architecture": "x86_64"
            }

**Comment by zqfan** [comment]
感谢您的反馈，已在https://github.com/TencentCloud/tencentcloud-sdk-java/commit/59d9be9ee67aad47def95a134430066074ca58e7 中修复
