### ISSUE TITLE
如何跑通demo

### ISSUE THREAD

**Issue by zunpan** [TencentCloud/tencentcloud-sdk-java#118]
简化版和详细版都试了一下，把SecretId和SecretKey替换成自己的了。
报错如下

java.lang.IllegalArgumentException: value == null

	at com.squareup.okhttp.Headers$Builder.add(Headers.java:231)
	at com.squareup.okhttp.Headers$Builder.set(Headers.java:265)
	at com.squareup.okhttp.Request$Builder.header(Request.java:165)
	at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:649)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:217)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.tencentcloudapi.common.TCLog.intercept(TCLog.java:56)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:225)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at com.tencentcloudapi.common.http.HttpConnection.doRequest(HttpConnection.java:60)
	at com.tencentcloudapi.common.http.HttpConnection.postRequest(HttpConnection.java:134)
	at com.tencentcloudapi.common.AbstractClient.doRequestWithTC3(AbstractClient.java:496)
	at com.tencentcloudapi.common.AbstractClient.internalRequest(AbstractClient.java:314)
	at cn.echaincity.osec.mobileapp.util.trtc.TrtcClient.DescribeRealtimeNetwork(TrtcClient.java:216)
	at cn.echaincity.osec.mobileapp.TrtcClientTest.test2(TrtcClientTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

**Comment by zqfan** [comment]
密钥打码，把你代码贴一下吧，这个堆栈看起来作用不大

**Comment by zunpan** [comment]
> 密钥打码，把你代码贴一下吧
> 另外也发一下你的okhttp版本，堆栈看起来已经进入到请求发送阶段了，这个报错我也不知道是怎么跑出来的

简化版demo
```java
@Test
    public void test2() {
        try {
            String SecretId = "***";
            String SecretKey = "***";

            Credential cred = new Credential(SecretId, SecretKey);
            CvmClient client = new CvmClient(cred, "ap-shanghai");

            DescribeInstancesRequest req = new DescribeInstancesRequest();
            DescribeInstancesResponse resp = client.DescribeInstances(req);

            System.out.println(DescribeInstancesResponse.toJsonString(resp));
        } catch (TencentCloudSDKException e) {
            System.out.println(e.toString());
        }
    }
```

其他接口，如trtc下的DescribePicture也是这个错误
```java
@Test
    public void test3() {
        try{
            String SecretId = "***";
            String SecretKey = "***";
            Credential cred = new Credential(SecretId, SecretKey);

            HttpProfile httpProfile = new HttpProfile();
            httpProfile.setEndpoint("trtc.tencentcloudapi.com");

            ClientProfile clientProfile = new ClientProfile();
            clientProfile.setHttpProfile(httpProfile);

            TrtcClient client = new TrtcClient(cred, "ap-guangzhou", clientProfile);

            DescribePictureRequest req = new DescribePictureRequest();
            req.setSdkAppId(***);

            DescribePictureResponse resp = client.DescribePicture(req);

            System.out.println(DescribePictureResponse.toJsonString(resp));
        } catch (TencentCloudSDKException e) {
            System.out.println(e.toString());
        }
    }
```

接口能在API Explore跑通，本地报错信息就是上面的堆栈信息

**Comment by zqfan** [comment]
sdk依赖的是okhttp==2.5.0，3.14应该是不兼容的

**Comment by zunpan** [comment]
谢谢，已经解决了
