### ISSUE TITLE
使用代理访问服务发生异常

### ISSUE THREAD

**Issue by chenjx-0** [TencentCloud/tencentcloud-sdk-java#125]
httpProfile.setProxyHost();
httpProfile.setProxyPort();
通过以上两个方法设置代理服务器，请求调用返回状态码400，
错误：TencentCloudSDKException: java.io.IOException-Unexpected response code for CONNECT: 400
 at com.tencentcloudapi.common.http.HttpConnection.doRequest(HttpConnection.java:62) ~[tencentcloud-sdk-java-3.1.268.jar!/:na]
不使用以上两个方法，在启动时指定http代理，错误：
TencentCloudSDKException: java.net.UnknownHostException-asr.tencentcloudapi.com: Name or service not known
	at com.tencentcloudapi.common.http.HttpConnection.doRequest(HttpConnection.java:62) ~[tencentcloud-sdk-java-3.1.268.jar!/:na]
	at com.tencentcloudapi.common.http.HttpConnection.postRequest(HttpConnection.java:134) ~[tencentcloud-sdk-java-3.1.268.jar!/:na]

**Comment by zqfan** [comment]
如果不涉密，把代理的值给一下
此外，注意代理是否本身有账号密码，sdk应该是支持带密码的代理
