### ISSUE TITLE
调用文本安全接口报偶尔报 java.net.ProtocolException-Too many follow-up requests: 21异常

### ISSUE THREAD

**Issue by ITGcx** [TencentCloud/tencentcloud-sdk-java#168]
[2022-08-22 14:55:38]
content: 
com.tencentcloudapi.common.exception.TencentCloudSDKException: java.net.ProtocolException-Too many follow-up requests: 21
+2
[2022-08-22 14:55:38]
content: 
	at com.tencentcloudapi.common.http.HttpConnection.doRequest(HttpConnection.java:62)
+3
[2022-08-22 14:55:38]
content: 
	at com.tencentcloudapi.common.http.HttpConnection.postRequest(HttpConnection.java:134)
+4
[2022-08-22 14:55:38]
content: 
	at com.tencentcloudapi.common.AbstractClient.doRequestWithTC3(AbstractClient.java:498)
+5
[2022-08-22 14:55:38]
content: 
	at com.tencentcloudapi.common.AbstractClient.internalRequest(AbstractClient.java:316)
+6
[2022-08-22 14:55:38]
content: 
	at com.tencentcloudapi.tms.v20200713.TmsClient.TextModeration(TmsClient.java:113)

**Comment by zqfan** [comment]
有经过代理吗？这种报错可能是302跳转太多引起的
