### ISSUE TITLE
javax.net.ssl.SSLException-java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by ChenGuop** [TencentCloud/tencentcloud-sdk-java#244]
人脸搜索异常-重启服务网后就正常了:
2024-12-24 08:42:15.768 ERROR 1 --- [nio-8356-exec-4] com.anzhong.common.face.CreateGroup      : 人脸搜索

com.tencentcloudapi.common.exception.TencentCloudSDKException: javax.net.ssl.SSLException-java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at com.tencentcloudapi.common.http.HttpConnection.doRequest(HttpConnection.java:52) ~[tencentcloud-sdk-java-3.0.70.jar!/:na]
        at com.tencentcloudapi.common.http.HttpConnection.postRequest(HttpConnection.java:98) ~[tencentcloud-sdk-java-3.0.70.jar!/:na]
        at com.tencentcloudapi.common.AbstractClient.doRequest(AbstractClient.java:313) ~[tencentcloud-sdk-java-3.0.70.jar!/:na]
        at com.tencentcloudapi.common.AbstractClient.internalRequest(AbstractClient.java:269) ~[tencentcloud-sdk-java-3.0.70.jar!/:na]
        at com.tencentcloudapi.iai.v20180301.IaiClient.SearchFaces(IaiClient.java:447) ~[tencentcloud-sdk-java-3.0.70.jar!/:na]

**Comment by zqfan** [comment]
可更新sdk版本试下能否解决
        <dependency>
            <groupId>com.tencentcloudapi</groupId>
            <artifactId>tencentcloud-sdk-java</artifactId>
            <version>3.1.1138</version>
        </dependency>
