### ISSUE TITLE
此SDK ANDROID使用出现 Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found

### ISSUE THREAD

**Issue by k3sc** [TencentCloud/tencentcloud-sdk-java#54]
RTjava.lang.Error: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found
        at javax.xml.bind.DatatypeConverterImpl.<clinit>(DatatypeConverterImpl.java:907)
        at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155)
        at javax.xml.bind.DatatypeConverter.printHexBinary(DatatypeConverter.java:640)
        at com.tencentcloudapi.common.Sign.sha256Hex(Sign.java:107)
        at com.tencentcloudapi.common.AbstractClient.doRequestWithTC3(AbstractClient.java:355)
        at com.tencentcloudapi.common.AbstractClient.internalRequest(AbstractClient.java:267)
        at com.tencentcloudapi.ocr.v20181119.OcrClient.BizLicenseOCR(OcrClient.java:98)
        at com.yinet.ocr.BuLicenActivity.onActivityResult(BuLicenActivity.java:85)
        at android.app.Activity.dispatchActivityResult(Activity.java:6192)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3575)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3622)
        at android.app.ActivityThread.access$1300(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5293)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found
        at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:106)
        at javax.xml.bind.DatatypeConverterImpl.<clinit>(DatatypeConverterImpl.java:905)
        at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155) 
        at javax.xml.bind.DatatypeConverter.printHexBinary(DatatypeConverter.java:640) 
        at com.tencentcloudapi.common.Sign.sha256Hex(Sign.java:107) 
        at com.tencentcloudapi.common.AbstractClient.doRequestWithTC3(AbstractClient.java:355) 
        at com.tencentcloudapi.common.AbstractClient.internalRequest(AbstractClient.java:267) 
        at com.tencentcloudapi.ocr.v20181119.OcrClient.BizLicenseOCR(OcrClient.java:98) 
        at com.yinet.ocr.BuLicenActivity.onActivityResult(BuLicenActivity.java:85) 
        at android.app.Activity.dispatchActivityResult(Activity.java:6192) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3575) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3622) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5293) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl" on path: DexPathList[[zip file "/data/app/com.yinet.ocr-2/base.apk"],nativeLibraryDirectories=[/data/app/com.yinet.ocr-2/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at javax.xml.datatype.FactoryFinder.newInstance(FactoryFinder.java:138)
        at javax.xml.datatype.FactoryFinder.find(FactoryFinder.java:219)
        at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:99)
        at javax.xml.bind.DatatypeConverterImpl.<clinit>(DatatypeConverterImpl.java:905) 
        at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:155) 
        at javax.xml.bind.DatatypeConverter.printHexBinary(DatatypeConverter.java:640) 
        at com.tencentcloudapi.common.Sign.sha256Hex(Sign.java:107) 
        at com.tencentcloudapi.common.AbstractClient.doRequestWithTC3(AbstractClient.java:355) 
        at com.tencentcloudapi.common.AbstractClient.internalRequest(AbstractClient.java:267) 
        at com.tencentcloudapi.ocr.v20181119.OcrClient.BizLicenseOCR(OcrClient.java:98) 
        at com.yinet.ocr.BuLicenActivity.onActivityResult(BuLicenActivity.java:85) 
        at android.app.Activity.dispatchActivityResult(Activity.java:6192) 
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3575) 
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3622) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5293) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    	Suppressed: java.lang.ClassNotFoundException: org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 24 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by zqfan** [comment]
这是java的sdk，并没有进行android兼容测。
如果只是缺包，你直接添加缺失的包为依赖试试能否解决

**Comment by fantouch** [comment]
解决办法见 https://github.com/TencentCloud/tencentcloud-sdk-java/issues/26#issuecomment-481558410
