### ISSUE TITLE
Java9以及Java10默认不再加载JAXB

### ISSUE THREAD

**Issue by wsy** [TencentCloud/tencentcloud-sdk-java#6]
Java9开始，默认不再加载JAXB，javax.xml.bind默认不再可用。而你们的pom的dependency里又没有加上jaxb的依赖，导致Runtime类加载异常。
以下是部分堆栈。
```
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[na:na]
	at com.tencentcloudapi.common.Sign.sign(Sign.java:53) ~[tencentcloud-sdk-java-3.0.1.jar:na]

```

**Comment by louishlz** [comment]
多谢提醒，我们下个版本解决下
